### ISSUE TITLE
COPY failed: file not found in build context or excluded by .dockerignore: stat prod.env: file does not exist

### ISSUE THREAD

**Issue by guanyintu** [tbrittain/OWL-API#1]
Is this the .env file that the documentation says?

**Comment by tbrittain** [comment]
Hey there, thanks for bringing this to my attention. This should be fixed by removing [line 7](https://github.com/tbrittain/OWL-API/blob/master/dbUpdate/Dockerfile#L7) from the Dockerfile in the dbUpdate module.

**Comment by tbrittain** [comment]
I also realize now that there will likely be another issue soon after you get past this step, though. I cannot update the code with these fixes at the moment, but if you are able to, have [this function](https://github.com/tbrittain/OWL-API/blob/master/dbUpdate/src/utils.py#L73) return a default timestamp if no rows are found (which will occur when no data present in the database for it to pull from).
